In [3]:



# Lectura de los archivos
import pandas as pd

url = (
    "https://raw.githubusercontent.com/"
    "jdvelasq/datalabs/master/datasets/precio_bolsa_nacional/csv/{}.csv"
)

org_df = pd.concat([pd.read_csv(url.format(fecha)) for fecha in fechas])
org_df.head()

,Fecha,0,1,2,3,4,5,6,7,8,...,14,15,16,17,18,19,20,21,22,23
0,1995-07-21,1.073,1.0,1.0,1.0,1.0,1.0,5.0,6.0,6.0,...,5.0,1.0,1.0,5.0,12.0,16.67,11.929,5.0,1.0,1.0
1,1995-07-22,1.073,1.073,1.0,1.0,1.0,1.073,1.303,1.303,1.303,...,1.073,1.0,1.0,1.0,1.303,2.5,2.5,1.303,1.073,1.073
2,1995-07-23,1.073,1.0,1.0,1.0,1.0,1.0,0.1,1.0,1.0,...,1.0,0.1,0.1,1.0,1.238,1.238,1.238,1.238,1.073,1.0
3,1995-07-24,1.0,1.0,0.99,1.0,1.0,1.073,3.0,3.0,3.0,...,1.073,1.073,3.0,2.0,18.63,22.5,9.256,3.0,1.073,1.0
4,1995-07-25,0.99,0.99,0.989,0.99,0.99,1.073,1.263,1.263,1.263,...,1.073,1.073,1.073,1.073,1.263,1.5,1.263,1.263,1.073,0.99

In [ ]:
# Creación del vector de fechas
fechas = [
    "{:4d}{:02d}".format(year, month)
    for year in range(1995, 2022)
    for month in range(1, 13)
]
fechas = [fecha for fecha in fechas if fecha >= "199507" and fecha <= "202104"]
fechas[0], fechas[-1], len(fechas)


# Lectura de los archivos
import pandas as pd

url = (
    "https://raw.githubusercontent.com/"
    "jdvelasq/datalabs/master/datasets/precio_bolsa_nacional/csv/{}.csv"
)

org_df = pd.concat([pd.read_csv(url.format(fecha)) for fecha in fechas])
org_df.head()







# Manipulacion del dataframe
melted_df = pd.melt(
    org_df,
    id_vars="Fecha",
    var_name="Hora",
    value_name="Precio",
)
melted_df = melted_df.sort_values(["Fecha", "Hora"]).reset_index(drop=True)
melted_df.head()





# Verificación de los tipos para buscar problemas
melted_df.dtypes



# Registros con precios NA
melted_df.Precio.isna().sum()




# Tamaño original del dataframe
melted_df.shape



# Eliminación de NA y tamaño final del dataframe
melted_df = melted_df.dropna()
melted_df.shape




# Búsqueda de registros con str en los precios
melted_df[melted_df["Precio"].map(lambda x: isinstance(x, str))].sort_values("Precio")




# Se elimina el '.' de los miles
melted_df["Precio"] = melted_df["Precio"].map(
    lambda x: x.replace(".", "") if isinstance(x, str) else x
)

c

# Vefificación
melted_df["Precio"][melted_df["Precio"].map(lambda x: isinstance(x, str))].sort_values()



# Revisión de los tipos de datos
melted_df.dtypes




# Cálculo de los precios diarios y renombramiento de la columna
precios_df = melted_df.groupby(["Fecha"]).agg({"Precio": "mean"})
precios_df = precios_df.rename(columns={"Precio": "Precio diario"})
precios_df.head()



# Tranformación del indice a tipo fecha
precios_df.index = pd.to_datetime(precios_df.index)

# Cálculo del precio promedio por mes
precios_df["Precio mensual"] = precios_df.groupby(
    [precios_df.index.year, precios_df.index.month]
)["Precio diario"].transform("mean")

precios_df.head()






import os
import matplotlib.pyplot as plt

precios_df.plot(style=["gray", "k"], figsize=(8, 3))
plt.xticks(rotation="vertical", fontsize=8)
plt.yticks(fontsize=8)
plt.gca().spines["left"].set_color("gray")
plt.gca().spines["bottom"].set_color("gray")
plt.gca().spines["top"].set_visible(False)
plt.gca().spines["right"].set_visible(False)
plt.legend(fontsize=8)

if os.path.exists("../files/images") is False:
    os.makedirs("../files/images")

plt.savefig("../files/images/precios.png", bbox_inches="tight")

plt.show()